export const PERMISSIONS = {
  DASHBOARD_VIEW: 'dashboard.view',
  DASHBOARD_CEO_VIEW: 'dashboard.ceo.view',
  DASHBOARD_CENTRO_EXECUTIVO_VIEW: 'dashboard.centro-executivo.view',
  DASHBOARD_EXECUTIVO_VIEW: 'dashboard.executivo.view',
  DASHBOARD_DIRETOR_VIEW: 'dashboard.diretor.view',
  DASHBOARD_GERENTE_VIEW: 'dashboard.gerente.view',
  DASHBOARD_RH_VIEW: 'dashboard.rh.view',
  DASHBOARD_SUPRIMENTOS_VIEW: 'dashboard.suprimentos.view',
  DASHBOARD_ENGENHARIA_VIEW: 'dashboard.engenharia.view',
  DASHBOARD_EXPORTAR: 'dashboard.exportar',
  DASHBOARD_USUARIO_PERSONALIZAR: 'dashboard.usuario.personalizar',
  NOTIFICACOES_VIEW: 'notificacoes.view',
  NOTIFICACOES_CONFIGURAR: 'notificacoes.configurar',
  NOTIFICACOES_EMAIL_FILA_VIEW: 'notificacoes.email-fila.view',
  NOTIFICACOES_EMAIL_FILA_REPROCESSAR: 'notificacoes.email-fila.reprocessar',
  NOTIFICACOES_TEMPLATES_ADMIN: 'notificacoes.templates.admin',
  RELATORIOS_AGENDADOS_VIEW: 'relatorios.agendados.view',
  RELATORIOS_AGENDADOS_CRUD: 'relatorios.agendados.crud',
  RELATORIOS_AGENDADOS_EXECUTAR: 'relatorios.agendados.executar',
  RELATORIOS_AGENDADOS_AUDITORIA: 'relatorios.agendados.auditoria',

  BUSCA_GLOBAL_VIEW: 'busca.global.view',
  BUSCA_GLOBAL_REINDEXAR: 'busca.global.reindexar',

  AUTOMACOES_VIEW: 'automacoes.view',
  AUTOMACOES_CRUD: 'automacoes.crud',
  AUTOMACOES_EXECUTAR: 'automacoes.executar',
  AUTOMACOES_AUDITORIA: 'automacoes.auditoria',
  AUTOMACOES_SLA_VIEW: 'automacoes.sla.view',
  AUTOMACOES_SLA_CRUD: 'automacoes.sla.crud',

  APROVACOES_VIEW: 'aprovacoes.view',
  APROVACOES_DECIDIR: 'aprovacoes.decidir',
  APROVACOES_MODELOS_VIEW: 'aprovacoes.modelos.view',
  APROVACOES_MODELOS_CRUD: 'aprovacoes.modelos.crud',
  APROVACOES_AUDITORIA: 'aprovacoes.auditoria',
  APROVACOES_ASSINAR: 'aprovacoes.assinar',

  WORKFLOWS_VIEW: 'workflows.view',
  WORKFLOWS_CRUD: 'workflows.crud',
  WORKFLOWS_EXECUTAR: 'workflows.executar',
  WORKFLOWS_AUDITORIA: 'workflows.auditoria',
  WORKFLOWS_MODELOS_VIEW: 'workflows.modelos.view',
  WORKFLOWS_MODELOS_CRUD: 'workflows.modelos.crud',
  WORKFLOWS_ASSINAR: 'workflows.assinar',
  WORKFLOWS_DESIGNER_VIEW: 'workflows.designer.view',
  WORKFLOWS_DESIGNER_CRUD: 'workflows.designer.crud',
  WORKFLOWS_PUBLICAR: 'workflows.publicar',
  WORKFLOWS_SIMULAR: 'workflows.simular',
  PORTAL_GESTOR_VIEW: 'portal.gestor.view',
  PORTAL_GESTOR_OPERAR: 'portal.gestor.operar',
  PORTAL_GESTOR_ATALHOS: 'portal.gestor.atalhos',
  PORTAL_GESTOR_EQUIPE_VIEW: 'portal.gestor.equipe.view',
  PORTAL_GESTOR_PENDENCIAS_VIEW: 'portal.gestor.pendencias.view',
  MOBILE_APP_VIEW: 'mobile.app.view',
  MOBILE_PUSH_ADMIN: 'mobile.push.admin',
  MOBILE_DEVICE_AUDITORIA: 'mobile.device.auditoria',
  ANALYTICS_VIEW: 'analytics.view',
  ANALYTICS_ADMIN: 'analytics.admin',
  ANALYTICS_CARGAS_VIEW: 'analytics.cargas.view',
  ANALYTICS_CARGAS_EXECUTAR: 'analytics.cargas.executar',
  ANALYTICS_EXTERNOS_VIEW: 'analytics.externos.view',
  ANALYTICS_EXTERNOS_CRUD: 'analytics.externos.crud',
  PARCEIROS_EMPRESAS_VIEW: 'parceiros.empresas.view',
  PARCEIROS_EMPRESAS_CRUD: 'parceiros.empresas.crud',
  PARCEIROS_USUARIOS_CRUD: 'parceiros.usuarios.crud',
  PARCEIROS_DOCUMENTOS_VALIDAR: 'parceiros.documentos.validar',
  PARCEIROS_CONFORMIDADE_VIEW: 'parceiros.conformidade.view',
  PORTAL_PARCEIRO_VIEW: 'portal.parceiro.view',
  PORTAL_PARCEIRO_TRABALHADORES_VIEW: 'portal.parceiro.trabalhadores.view',
  PORTAL_PARCEIRO_DOCUMENTOS_VIEW: 'portal.parceiro.documentos.view',
  PORTAL_PARCEIRO_DOCUMENTOS_ENVIAR: 'portal.parceiro.documentos.enviar',
  PORTAL_PARCEIRO_TREINAMENTOS_VIEW: 'portal.parceiro.treinamentos.view',
  PORTAL_PARCEIRO_EPI_VIEW: 'portal.parceiro.epi.view',
  PORTAL_PARCEIRO_INTEGRACOES_VIEW: 'portal.parceiro.integracoes.view',
  PORTAL_PARCEIRO_NOTIFICACOES_VIEW: 'portal.parceiro.notificacoes.view',
  SECURITY_POLICIES_VIEW: 'security.policies.view',
  SECURITY_POLICIES_CRUD: 'security.policies.crud',
  SECURITY_POLICIES_SIMULAR: 'security.policies.simular',
  SECURITY_POLICIES_AUDITORIA: 'security.policies.auditoria',
  SECURITY_POLICIES_REINDEXAR: 'security.policies.reindexar',

  PWA_CONFIGURAR: 'pwa.configurar',
  PUSH_NOTIFICACOES_ADMIN: 'push.notificacoes.admin',
  SYNC_OFFLINE_AUDITORIA_VIEW: 'sync.offline.auditoria.view',
  SYNC_OFFLINE_REPROCESSAR: 'sync.offline.reprocessar',

  DOCUMENTOS_VIEW: 'documentos.view',
  DOCUMENTOS_CRUD: 'documentos.crud',
  DOCUMENTOS_ASSINAR: 'documentos.assinar',
  DOCUMENTOS_VERIFICAR: 'documentos.verificar',
  DOCUMENTOS_MODELOS_VIEW: 'documentos.modelos.view',
  DOCUMENTOS_MODELOS_CRUD: 'documentos.modelos.crud',
  DOCUMENTOS_AUDITORIA: 'documentos.auditoria',

  OBRAS_VIEW: 'obras.view',
  MAPA_OBRAS_VIEW: 'obras.mapa.view',

  CONFIG_EMPRESA_VIEW: 'config.empresa.view',
  CONFIG_EMPRESA_EDIT: 'config.empresa.edit',

  REPRESENTANTE_VIEW: 'config.representante.view',
  REPRESENTANTE_EDIT: 'config.representante.edit',

  ENCARREGADO_SISTEMA_VIEW: 'config.encarregado.view',
  ENCARREGADO_SISTEMA_EDIT: 'config.encarregado.edit',
  ENCARREGADO_SISTEMA_SOLICITAR_SAIDA: 'config.encarregado.solicitar_saida',

  GOVERNANCA_VIEW: 'admin.governanca.view',
  GOVERNANCA_USUARIOS_CRUD: 'admin.governanca.usuarios.crud',
  GOVERNANCA_PERFIS_CRUD: 'admin.governanca.perfis.crud',
  GOVERNANCA_ABRANGENCIA_CRUD: 'admin.governanca.abrangencia.crud',

  BACKUP_VIEW: 'admin.backup.view',
  BACKUP_EDIT: 'admin.backup.edit',
  BACKUP_RESTORE_REQUEST: 'admin.backup.restore.request',

  ORGANOGRAMA_VIEW: 'organograma.estrutura.view',
  ORGANOGRAMA_CRUD: 'organograma.estrutura.crud',

  RH_FUNCIONARIOS_VIEW: 'rh.funcionarios.view',
  RH_FUNCIONARIOS_CRUD: 'rh.funcionarios.crud',
  RH_FUNCIONARIOS_ENDOSSAR: 'rh.funcionarios.endossar',

  RH_HORAS_EXTRAS_VIEW: 'rh.horas_extras.view',
  RH_HORAS_EXTRAS_CRUD: 'rh.horas_extras.crud',
  RH_HORAS_EXTRAS_PROCESSAR: 'rh.horas_extras.processar',

  RH_PRESENCAS_VIEW: 'rh.presencas.view',
  RH_PRESENCAS_CRUD: 'rh.presencas.crud',
  RH_PRESENCAS_FECHAR: 'rh.presencas.fechar',
  RH_PRESENCAS_ENVIAR: 'rh.presencas.enviar_rh',
  RH_PRESENCAS_RECEBER: 'rh.presencas.receber_rh',

  RH_ASSINATURAS_EXECUTAR: 'rh.assinaturas.executar',

  SST_EPI_VIEW: 'sst.epi.view',
  SST_EPI_CRUD: 'sst.epi.crud',
  SST_EPI_ENTREGA: 'sst.epi.entrega',
  SST_EPI_DEVOLUCAO: 'sst.epi.devolucao',
  SST_EPI_INSPECAO: 'sst.epi.inspecao',
  SST_EPI_ASSINAR: 'sst.epi.assinar',
  SST_TECNICOS_VIEW: 'sst.tecnicos.view',
  SST_TECNICOS_CRUD: 'sst.tecnicos.crud',

  SST_CHECKLISTS_VIEW: 'sst.checklists.view',
  SST_CHECKLISTS_CRUD: 'sst.checklists.crud',
  SST_CHECKLISTS_EXECUTAR: 'sst.checklists.executar',
  SST_CHECKLISTS_FINALIZAR: 'sst.checklists.finalizar',
  SST_CHECKLISTS_ASSINAR: 'sst.checklists.assinar',

  SST_NC_VIEW: 'sst.nao_conformidades.view',
  SST_NC_CRUD: 'sst.nao_conformidades.crud',
  SST_NC_TRATAR: 'sst.nao_conformidades.tratar',
  SST_NC_VALIDAR: 'sst.nao_conformidades.validar',
  SST_NC_ENCERRAR: 'sst.nao_conformidades.encerrar',

  SST_TREINAMENTOS_VIEW: 'sst.treinamentos.view',
  SST_TREINAMENTOS_CRUD: 'sst.treinamentos.crud',
  SST_TREINAMENTOS_EXECUTAR: 'sst.treinamentos.executar',
  SST_TREINAMENTOS_ASSINAR: 'sst.treinamentos.assinar',
  SST_TREINAMENTOS_FINALIZAR: 'sst.treinamentos.finalizar',
  SST_TREINAMENTOS_CERTIFICAR: 'sst.treinamentos.certificar',

  SST_ACIDENTES_VIEW: 'sst.acidentes.view',
  SST_ACIDENTES_CRUD: 'sst.acidentes.crud',
  SST_ACIDENTES_INVESTIGAR: 'sst.acidentes.investigar',
  SST_ACIDENTES_VALIDAR: 'sst.acidentes.validar',
  SST_ACIDENTES_ENCERRAR: 'sst.acidentes.encerrar',
  SST_ACIDENTES_CAT: 'sst.acidentes.cat',

  SST_PAINEL_VIEW: 'sst.painel.view',
  SST_PAINEL_EXECUTIVO_VIEW: 'sst.painel.executivo.view',

  FUNCIONARIOS_VIEW: 'rh.funcionarios.view',
  FUNCIONARIOS_CRUD: 'rh.funcionarios.crud',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PROFILE_CODES = {
  CEO: 'CEO',
  REPRESENTANTE_EMPRESA: 'REPRESENTANTE_EMPRESA',
  ENCARREGADO_SISTEMA_EMPRESA: 'ENCARREGADO_SISTEMA_EMPRESA',
  DIRETOR: 'DIRETOR',
  GERENTE_RH: 'GERENTE_RH',
  ADMIN_RH: 'ADMIN_RH',
  SST_TECNICO: 'SST_TECNICO',
} as const;

export type ProfileCode = (typeof PROFILE_CODES)[keyof typeof PROFILE_CODES];
