services:
  - type: web
    name: expplanobras-backend
    rootDir: backend
    env: node
    plan: free
    buildCommand: |
      set -e
      npm ci --include=dev
      npx prisma generate --schema=./prisma/postgres/schema.prisma
      cd prisma/postgres && npx prisma migrate deploy --schema=./schema.prisma && cd ../..
      npm run create-system-admin
      npm run build
    startCommand: |
      node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
