export const PLAYBOOK_MODES = ['MANUAL', 'SEMI_AUTOMATICO', 'AUTOMATICO'];
export const PLAYBOOK_TRIGGERS = ['ALERTA_ABERTO', 'ALERTA_CRITICO', 'INCIDENTE_ABERTO', 'EVENTO_CORRELACIONADO', 'AGENDADO', 'MANUAL'];
export const PLAYBOOK_RISK_LEVELS = ['BAIXO', 'MEDIO', 'ALTO', 'CRITICO'];
export const PLAYBOOK_APPROVAL_POLICIES = ['NAO_EXIGE', 'EXIGE_ANTES', 'EXIGE_SE_RISCO_ALTO', 'QUATRO_OLHOS'];
export const PLAYBOOK_EXEC_STATUSES = ['PENDENTE_APROVACAO', 'AGENDADA', 'EXECUTANDO', 'CONCLUIDA', 'PARCIAL', 'FALHA', 'CANCELADA'];
export const PLAYBOOK_STEP_STATUSES = ['PENDENTE', 'EXECUTANDO', 'CONCLUIDO', 'FALHA', 'IGNORADO', 'ROLLBACK_EXECUTADO'];
