import { PERMISSIONS } from '@/lib/auth/permissions';
import type { MenuSectionConfig } from './types';

export const APP_MENU: MenuSectionConfig[] = [
  {
    key: 'principal',
    label: 'Principal',
    ordem: 1,
    items: [
      {
        key: 'config-empresa-representante',
        label: 'Painel do Representante',
        icon: 'settings',
        permission: PERMISSIONS.REPRESENTANTE_VIEW,
        scopeTypes: ['EMPRESA'],
        children: [
          {
            key: 'painel-representante-dashboard',
            label: 'Dashboard',
            href: '/dashboard/config/representante/dashboard',
            icon: 'layout-dashboard',
            permission: PERMISSIONS.REPRESENTANTE_VIEW,
            scopeTypes: ['EMPRESA'],
            homePriority: 0,
          },
          {
            key: 'painel-representante-configuracoes',
            label: 'Configurações',
            href: '/dashboard/config/representante/configuracoes',
            icon: 'settings',
            permission: PERMISSIONS.REPRESENTANTE_VIEW,
            scopeTypes: ['EMPRESA'],
          },
        ],
      },
      {
        key: 'dashboard-ceo',
        label: 'Dashboard CEO',
        href: '/dashboard/ceo',
        icon: 'layout-dashboard',
        permission: PERMISSIONS.DASHBOARD_CEO_VIEW,
        scopeTypes: ['EMPRESA', 'DIRETORIA'],
        homePriority: 1,
      },
      {
        key: 'dashboard-diretor',
        label: 'Dashboard Diretor',
        href: '/dashboard/diretor',
        icon: 'bar-chart-3',
        permission: PERMISSIONS.DASHBOARD_DIRETOR_VIEW,
        scopeTypes: ['DIRETORIA'],
        homePriority: 2,
      },
      {
        key: 'dashboard-gerente',
        label: 'Dashboard Gerente',
        href: '/dashboard/gerente',
        icon: 'briefcase',
        permission: PERMISSIONS.DASHBOARD_GERENTE_VIEW,
        scopeTypes: ['EMPRESA', 'DIRETORIA', 'OBRA', 'UNIDADE'],
        homePriority: 3,
      },
      {
        key: 'centro-executivo',
        label: 'Centro Executivo',
        href: '/dashboard/executivo/centro',
        icon: 'radar',
        permission: PERMISSIONS.DASHBOARD_CENTRO_EXECUTIVO_VIEW,
        scopeTypes: ['EMPRESA', 'DIRETORIA', 'OBRA', 'UNIDADE'],
        homePriority: 5,
      },
      {
        key: 'portal-gestor',
        label: 'Portal do Gestor',
        href: '/dashboard/gestor/portal',
        icon: 'construction',
        permission: PERMISSIONS.PORTAL_GESTOR_VIEW,
        scopeTypes: ['OBRA', 'UNIDADE', 'EMPRESA', 'DIRETORIA'],
        homePriority: 6,
      },
      {
        key: 'painel-engenharia',
        label: 'Painel Engenharia',
        href: '/dashboard/engenharia/painel',
        icon: 'hammer',
        permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
        scopeTypes: ['EMPRESA', 'DIRETORIA', 'OBRA', 'UNIDADE'],
        homePriority: 13,
      },
      {
        key: 'notificacoes',
        label: 'Notificações',
        href: '/dashboard/notificacoes',
        icon: 'bell',
        permission: PERMISSIONS.NOTIFICACOES_VIEW,
        homePriority: 9999,
      },
      {
        key: 'aprovacoes',
        label: 'Aprovações',
        href: '/dashboard/aprovacoes',
        icon: 'stamp',
        permission: PERMISSIONS.APROVACOES_VIEW,
        homePriority: 9997,
      },
      {
        key: 'workflows',
        label: 'Workflows',
        href: '/dashboard/workflows',
        icon: 'git-branch',
        permission: PERMISSIONS.WORKFLOWS_VIEW,
        homePriority: 9996,
      },
      {
        key: 'sincronizacao',
        label: 'Sincronização',
        href: '/dashboard/sincronizacao',
        icon: 'cloud-off',
        permission: PERMISSIONS.DASHBOARD_VIEW,
        homePriority: 9995,
      },
      {
        key: 'documentos',
        label: 'Documentos',
        href: '/dashboard/documentos',
        icon: 'file-text',
        permission: PERMISSIONS.DOCUMENTOS_VIEW,
        homePriority: 9994,
      },
      {
        key: 'busca-global',
        label: 'Busca',
        href: '/dashboard/busca',
        icon: 'search',
        permission: PERMISSIONS.BUSCA_GLOBAL_VIEW,
        homePriority: 9998,
      },
    ],
  },
  {
    key: 'rh',
    label: 'RH',
    ordem: 2,
    items: [
      {
        key: 'painel-rh',
        label: 'Painel RH',
        href: '/dashboard/rh/painel',
        icon: 'users',
        permission: PERMISSIONS.DASHBOARD_RH_VIEW,
        homePriority: 10,
      },
      {
        key: 'funcionarios',
        label: 'Pessoas (Cadastros)',
        href: '/dashboard/rh/cadastros',
        icon: 'id-card',
        permission: PERMISSIONS.RH_FUNCIONARIOS_VIEW,
      },
      {
        key: 'presencas',
        label: 'Presenças',
        href: '/dashboard/rh/presencas',
        icon: 'clipboard-check',
        permission: PERMISSIONS.RH_PRESENCAS_VIEW,
      },
      {
        key: 'produtividade',
        label: 'Produtividade (Obra)',
        href: '/dashboard/rh/produtividade',
        icon: 'line-chart',
        permission: PERMISSIONS.DASHBOARD_RH_VIEW,
      },
    ],
  },
  {
    key: 'sst',
    label: 'SST',
    ordem: 3,
    items: [
      {
        key: 'painel-sst',
        label: 'Painel SST',
        href: '/dashboard/sst/painel',
        icon: 'shield',
        permission: PERMISSIONS.SST_PAINEL_VIEW,
        homePriority: 11,
      },
      {
        key: 'epi',
        label: 'EPI',
        href: '/dashboard/sst/epi',
        icon: 'hard-hat',
        permission: PERMISSIONS.SST_EPI_VIEW,
      },
      {
        key: 'tecnicos',
        label: 'Técnicos SST',
        href: '/dashboard/sst/tecnicos',
        icon: 'stethoscope',
        permission: PERMISSIONS.SST_TECNICOS_VIEW,
      },
      {
        key: 'checklists',
        label: 'Checklists SST',
        href: '/dashboard/sst/checklists',
        icon: 'list-checks',
        permission: PERMISSIONS.SST_CHECKLISTS_VIEW,
      },
      {
        key: 'nao-conformidades',
        label: 'Não Conformidades',
        href: '/dashboard/sst/nao-conformidades',
        icon: 'triangle-alert',
        permission: PERMISSIONS.SST_NC_VIEW,
      },
      {
        key: 'treinamentos',
        label: 'Treinamentos',
        href: '/dashboard/sst/treinamentos',
        icon: 'graduation-cap',
        permission: PERMISSIONS.SST_TREINAMENTOS_VIEW,
      },
      {
        key: 'acidentes',
        label: 'Acidentes',
        href: '/dashboard/sst/acidentes',
        icon: 'ambulance',
        permission: PERMISSIONS.SST_ACIDENTES_VIEW,
      },
    ],
  },
  {
    key: 'engenharia',
    label: 'Engenharia',
    ordem: 4,
    items: [
      {
        key: 'engenharia-obras',
        label: 'Obras',
        href: '/dashboard/engenharia/obras',
        icon: 'construction',
        permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
      },
      {
        key: 'engenharia-orcamentos',
        label: 'Orçamentos',
        href: '/dashboard/engenharia/orcamentos',
        icon: 'calculator',
        permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
      },
      {
        key: 'engenharia-licitacoes',
        label: 'Licitações',
        href: '/dashboard/engenharia/licitacoes',
        icon: 'file-search',
        permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
      },
      {
        key: 'centros-custo',
        label: 'Centros de Custo',
        href: '/dashboard/engenharia/cadastros/centros-custo',
        icon: 'layers',
        permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
      },
      {
        key: 'config-apropriacao',
        label: 'Config. Apropriação',
        href: '/dashboard/engenharia/configuracoes/apropriacao',
        icon: 'sliders',
        permission: PERMISSIONS.CONFIG_EMPRESA_VIEW,
      },
      {
        key: 'contrapartes',
        label: 'Contrapartes',
        href: '/dashboard/engenharia/contrapartes',
        icon: 'handshake',
        permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
      },
      {
        key: 'contratos-locacao',
        label: 'Contratos (Locação/Serviço)',
        href: '/dashboard/engenharia/contratos-locacao',
        icon: 'file-text',
        permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
      },
      {
        key: 'ativos',
        label: 'Equipamentos e Ferramentas',
        href: '/dashboard/engenharia/ativos',
        icon: 'wrench',
        permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
      },
    ],
  },
  {
    key: 'suprimentos',
    label: 'Suprimentos',
    ordem: 5,
    items: [
      {
        key: 'painel-suprimentos',
        label: 'Painel Suprimentos',
        href: '/dashboard/suprimentos/painel',
        icon: 'package',
        permission: PERMISSIONS.DASHBOARD_SUPRIMENTOS_VIEW,
        homePriority: 12,
      },
    ],
  },
  {
    key: 'fiscalizacao',
    label: 'Fiscalização',
    ordem: 6,
    items: [
      {
        key: 'painel-fiscalizacao',
        label: 'Painel Fiscalização',
        href: '/dashboard/fiscalizacao/painel',
        icon: 'clipboard-check',
        permission: PERMISSIONS.DASHBOARD_FISCALIZACAO_VIEW,
      },
    ],
  },
  {
    key: 'administracao',
    label: 'Administração',
    ordem: 7,
    items: [
      { key: 'organograma', label: 'Organograma', href: '/dashboard/organograma', icon: 'network', permission: PERMISSIONS.ORGANOGRAMA_VIEW },
      {
        key: 'encarregado-sistema',
        label: 'Administração do Sistema',
        icon: 'shield',
        permission: PERMISSIONS.GOVERNANCA_VIEW,
        scopeTypes: ['EMPRESA'],
        children: [
          {
            key: 'encarregado-governanca',
            label: 'Usuários, Perfis e Permissões',
            href: '/dashboard/admin/governanca',
            icon: 'shield',
            permission: PERMISSIONS.GOVERNANCA_VIEW,
            scopeTypes: ['EMPRESA'],
          },
          {
            key: 'encarregado-backup',
            label: 'Backup e Segurança',
            href: '/dashboard/admin/backup',
            icon: 'database-backup',
            permission: PERMISSIONS.BACKUP_VIEW,
          },
          {
            key: 'encarregado-automacoes',
            label: 'Automações',
            href: '/dashboard/admin/automacoes',
            icon: 'workflow',
            permission: PERMISSIONS.AUTOMACOES_VIEW,
          },
          {
            key: 'encarregado-aprovacoes-modelos',
            label: 'Aprovações (Modelos)',
            href: '/dashboard/admin/aprovacoes-modelos',
            icon: 'route',
            permission: PERMISSIONS.APROVACOES_MODELOS_VIEW,
          },
          {
            key: 'encarregado-workflows-modelos',
            label: 'Workflows (Modelos)',
            href: '/dashboard/admin/workflows-modelos',
            icon: 'workflow',
            permission: PERMISSIONS.WORKFLOWS_MODELOS_VIEW,
          },
          {
            key: 'encarregado-workflows-designer',
            label: 'Designer de Workflow',
            href: '/dashboard/admin/workflows-designer',
            icon: 'wand-2',
            permission: PERMISSIONS.WORKFLOWS_DESIGNER_VIEW,
          },
          {
            key: 'encarregado-notificacoes-fila',
            label: 'Fila de E-mails',
            href: '/dashboard/admin/notificacoes/email-fila',
            icon: 'mail',
            permission: PERMISSIONS.NOTIFICACOES_EMAIL_FILA_VIEW,
          },
          {
            key: 'encarregado-notificacoes-templates',
            label: 'Templates de Notificação',
            href: '/dashboard/admin/notificacoes/templates',
            icon: 'file-text',
            permission: PERMISSIONS.NOTIFICACOES_TEMPLATES_ADMIN,
          },
        ],
      },
      {
        key: 'analytics',
        label: 'Analytics / BI',
        href: '/dashboard/admin/analytics',
        icon: 'chart-column',
        permission: PERMISSIONS.ANALYTICS_VIEW,
      },
      {
        key: 'governanca-dados',
        label: 'Governança de Dados',
        href: '/dashboard/admin/governanca-dados',
        icon: 'database',
        permission: PERMISSIONS.DATA_CATALOG_VIEW,
      },
      {
        key: 'retencao',
        label: 'Retenção e Legal Hold',
        href: '/dashboard/admin/retencao',
        icon: 'archive',
        permission: PERMISSIONS.RETENCAO_VIEW,
      },
      {
        key: 'observabilidade',
        label: 'Observabilidade',
        icon: 'activity',
        permission: PERMISSIONS.OBSERVABILIDADE_VIEW,
        children: [
          { key: 'observabilidade-timeline', label: 'Timeline', href: '/dashboard/admin/observabilidade', icon: 'activity', permission: PERMISSIONS.OBSERVABILIDADE_EVENTOS_VIEW },
          { key: 'observabilidade-playbooks', label: 'Playbooks', href: '/dashboard/admin/observabilidade/playbooks', icon: 'workflow', permission: PERMISSIONS.PLAYBOOKS_VIEW },
          { key: 'observabilidade-compliance', label: 'Compliance', href: '/dashboard/admin/observabilidade/compliance', icon: 'scale', permission: PERMISSIONS.INCIDENT_RESPONSE_COMPLIANCE_VIEW },
        ],
      },
      {
        key: 'continuidade',
        label: 'Continuidade',
        href: '/dashboard/admin/continuidade',
        icon: 'shield-check',
        permission: PERMISSIONS.BCP_VIEW,
        children: [
          { key: 'continuidade-planos', label: 'Planos', href: '/dashboard/admin/continuidade', icon: 'shield-check', permission: PERMISSIONS.BCP_VIEW },
          { key: 'continuidade-dr', label: 'DR', href: '/dashboard/admin/continuidade/dr', icon: 'database-backup', permission: PERMISSIONS.DR_VIEW },
          { key: 'continuidade-crises', label: 'Crises', href: '/dashboard/admin/continuidade/crises', icon: 'alert-triangle', permission: PERMISSIONS.CRISE_VIEW },
        ],
      },
      {
        key: 'grc',
        label: 'GRC',
        href: '/dashboard/admin/grc',
        icon: 'shield-alert',
        permission: PERMISSIONS.GRC_VIEW,
        children: [
          { key: 'grc-hub', label: 'Visão Geral', href: '/dashboard/admin/grc', icon: 'shield-alert', permission: PERMISSIONS.GRC_VIEW },
          { key: 'grc-riscos', label: 'Riscos', href: '/dashboard/admin/grc/riscos', icon: 'alert-triangle', permission: PERMISSIONS.GRC_RISCOS_VIEW },
          { key: 'grc-controles', label: 'Controles', href: '/dashboard/admin/grc/controles', icon: 'check-check', permission: PERMISSIONS.GRC_CONTROLES_VIEW },
          { key: 'grc-auditorias', label: 'Auditorias', href: '/dashboard/admin/grc/auditorias', icon: 'clipboard-list', permission: PERMISSIONS.GRC_AUDITORIAS_VIEW },
          { key: 'grc-achados', label: 'Achados', href: '/dashboard/admin/grc/achados', icon: 'file-warning', permission: PERMISSIONS.GRC_ACHADOS_VIEW },
          { key: 'grc-planos-acao', label: 'Planos de Ação', href: '/dashboard/admin/grc/planos-acao', icon: 'clipboard-check', permission: PERMISSIONS.GRC_PLANOS_ACAO_VIEW },
        ],
      },
      {
        key: 'seguranca-politicas',
        label: 'Políticas de Segurança',
        href: '/dashboard/admin/seguranca/politicas',
        icon: 'shield-check',
        permission: PERMISSIONS.SECURITY_POLICIES_VIEW,
      },
      {
        key: 'admin-notificacoes',
        label: 'Notificações (Admin)',
        children: [
          {
            key: 'admin-notificacoes-fila',
            label: 'Fila de E-mails',
            href: '/dashboard/admin/notificacoes/email-fila',
            icon: 'mail',
            permission: PERMISSIONS.NOTIFICACOES_EMAIL_FILA_VIEW,
          },
          {
            key: 'admin-notificacoes-templates',
            label: 'Templates',
            href: '/dashboard/admin/notificacoes/templates',
            icon: 'file-text',
            permission: PERMISSIONS.NOTIFICACOES_TEMPLATES_ADMIN,
          },
        ],
      },
    ],
  },
  {
    key: 'relatorios',
    label: 'Relatórios',
    ordem: 5,
    items: [
      {
        key: 'relatorios-agendados',
        label: 'Relatórios Agendados',
        href: '/dashboard/relatorios/agendados',
        icon: 'calendar-clock',
        permission: PERMISSIONS.RELATORIOS_AGENDADOS_VIEW,
      },
    ],
  },
];
