import { PERMISSIONS } from '@/lib/auth/permissions';
import type { MenuSectionConfig } from './types';

export const APP_MENU: MenuSectionConfig[] = [
  {
    key: 'principal',
    label: 'Painéis',
    ordem: 1,
    items: [
      {
        key: 'config-empresa-representante',
        label: 'Painel do Representante',
        icon: 'settings',
        permission: PERMISSIONS.REPRESENTANTE_VIEW,
        scopeTypes: ['EMPRESA'],
        children: [
          {
            key: 'painel-representante-dashboard',
            label: 'Dashboard',
            href: '/dashboard/config/representante/dashboard',
            icon: 'layout-dashboard',
            permission: PERMISSIONS.REPRESENTANTE_VIEW,
            scopeTypes: ['EMPRESA'],
            homePriority: 0,
          },
          {
            key: 'painel-representante-configuracoes',
            label: 'Configurações',
            href: '/dashboard/config/representante/configuracoes',
            icon: 'settings',
            permission: PERMISSIONS.REPRESENTANTE_VIEW,
            scopeTypes: ['EMPRESA'],
          },
        ],
      },
      {
        key: 'dashboard-ceo',
        label: 'Dashboard CEO',
        href: '/dashboard/ceo',
        icon: 'layout-dashboard',
        permission: PERMISSIONS.DASHBOARD_CEO_VIEW,
        scopeTypes: ['EMPRESA', 'DIRETORIA'],
        homePriority: 1,
      },
      {
        key: 'config-empresa',
        label: 'Configurações da Empresa',
        icon: 'settings',
        permission: PERMISSIONS.CONFIG_EMPRESA_VIEW,
        scopeTypes: ['EMPRESA'],
        children: [
          {
            key: 'config-apropriacao',
            label: 'Apropriação (Configuração)',
            href: '/dashboard/engenharia/configuracoes/apropriacao',
            icon: 'sliders',
            permission: PERMISSIONS.CONFIG_EMPRESA_VIEW,
            scopeTypes: ['EMPRESA'],
          },
        ],
      },
      {
        key: 'encarregado-sistema',
        label: 'Administração do Sistema',
        icon: 'shield',
        permission: PERMISSIONS.GOVERNANCA_VIEW,
        scopeTypes: ['EMPRESA'],
        homePriority: 1.5,
        children: [
          {
            key: 'encarregado-governanca',
            label: 'Usuários, Perfis e Permissões',
            href: '/dashboard/admin/governanca',
            icon: 'shield',
            permission: PERMISSIONS.GOVERNANCA_VIEW,
            scopeTypes: ['EMPRESA'],
          },
          {
            key: 'encarregado-backup',
            label: 'Backup e Segurança',
            href: '/dashboard/admin/backup',
            icon: 'database-backup',
            permission: PERMISSIONS.BACKUP_VIEW,
          },
          {
            key: 'encarregado-automacoes',
            label: 'Automações',
            href: '/dashboard/admin/automacoes',
            icon: 'workflow',
            permission: PERMISSIONS.AUTOMACOES_VIEW,
          },
          {
            key: 'encarregado-aprovacoes-modelos',
            label: 'Aprovações (Modelos)',
            href: '/dashboard/admin/aprovacoes-modelos',
            icon: 'route',
            permission: PERMISSIONS.APROVACOES_MODELOS_VIEW,
          },
          {
            key: 'encarregado-workflows-modelos',
            label: 'Workflows (Modelos)',
            href: '/dashboard/admin/workflows-modelos',
            icon: 'workflow',
            permission: PERMISSIONS.WORKFLOWS_MODELOS_VIEW,
          },
          {
            key: 'encarregado-workflows-designer',
            label: 'Designer de Workflow',
            href: '/dashboard/admin/workflows-designer',
            icon: 'wand-2',
            permission: PERMISSIONS.WORKFLOWS_DESIGNER_VIEW,
          },
          {
            key: 'encarregado-notificacoes-fila',
            label: 'Fila de E-mails',
            href: '/dashboard/admin/notificacoes/email-fila',
            icon: 'mail',
            permission: PERMISSIONS.NOTIFICACOES_EMAIL_FILA_VIEW,
          },
          {
            key: 'encarregado-notificacoes-templates',
            label: 'Templates de Notificação',
            href: '/dashboard/admin/notificacoes/templates',
            icon: 'file-text',
            permission: PERMISSIONS.NOTIFICACOES_TEMPLATES_ADMIN,
          },
        ],
      },
      {
        key: 'dashboard-diretor',
        label: 'Dashboard Diretor',
        href: '/dashboard/diretor',
        icon: 'bar-chart-3',
        permission: PERMISSIONS.DASHBOARD_DIRETOR_VIEW,
        scopeTypes: ['DIRETORIA'],
        homePriority: 2,
      },
    ],
  },
  {
    key: 'contratos',
    label: 'Contratos',
    ordem: 2,
    items: [
      {
        key: 'contratos-dashboard',
        label: 'Dashboard',
        href: '/dashboard/contratos/dashboard',
        icon: 'file-text',
        permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
        children: [
          {
            key: 'contratos-dashboard-gestao',
            label: 'Gestão de Contratos',
            href: '/dashboard/engenharia/contratos-locacao',
            icon: 'file-text',
            permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
          },
          {
            key: 'contratos-dashboard-aditivos',
            label: 'Aditivos',
            href: '/dashboard/contratos/aditivos',
            icon: 'file-pen',
            permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
          },
          {
            key: 'contratos-dashboard-documentos',
            label: 'Documentos do Contrato',
            href: '/dashboard/obras/documentos?tipo=CONTRATO',
            icon: 'paperclip',
            permission: PERMISSIONS.DOCUMENTOS_VIEW,
          },
          {
            key: 'contratos-dashboard-medicoes',
            label: 'Medições (por contrato)',
            href: '/dashboard/contratos/medicoes',
            icon: 'clipboard-check',
            permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
          },
          {
            key: 'contratos-dashboard-pagamentos',
            label: 'Pagamentos',
            href: '/dashboard/contratos/pagamentos',
            icon: 'dollar-sign',
            permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
          },
          {
            key: 'contrapartes',
            label: 'Contrapartes (Parceiros)',
            icon: 'handshake',
            permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
            children: [
              {
                key: 'contrapartes-cadastro',
                label: 'Cadastro de Pessoas (PF/PJ)',
                href: '/dashboard/engenharia/contrapartes',
                icon: 'id-card',
                permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
              },
              {
                key: 'contrapartes-empresas',
                label: 'Empresas',
                href: '/dashboard/engenharia/contrapartes',
                icon: 'building-2',
                permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
              },
              {
                key: 'contrapartes-contatos',
                label: 'Contatos',
                href: '/dashboard/engenharia/contrapartes',
                icon: 'contact',
                permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
              },
              {
                key: 'contrapartes-documentos',
                label: 'Documentos',
                href: '/dashboard/engenharia/contrapartes',
                icon: 'paperclip',
                permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    key: 'engenharia',
    label: 'Engenharia',
    ordem: 3,
    items: [
      {
        key: 'engenharia-dashboard',
        label: 'Dashboard Engenharia',
        href: '/dashboard/engenharia/painel',
        icon: 'layout-dashboard',
        permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
        homePriority: 13,
      },
      {
        key: 'engenharia-obras',
        label: 'Obras',
        icon: 'construction',
        permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
        children: [
          {
            key: 'engenharia-obras-selecionar',
            label: 'Selecionar Obra',
            href: '/dashboard/engenharia/obras',
            icon: 'arrow-left-right',
            permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
          },
          {
            key: 'engenharia-obras-ativa-dashboard',
            label: 'Dashboard da Obra',
            href: '/dashboard/engenharia/obras/ativa/dashboard',
            icon: 'layout-dashboard',
            permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
          },
          {
            key: 'engenharia-obras-ativa-contrato',
            label: 'Resumo do Contrato',
            href: '/dashboard/engenharia/obras/ativa/contrato',
            icon: 'file-text',
            permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
          },
          {
            key: 'engenharia-obras-ativa-documentos',
            label: 'Documentos da Obra',
            href: '/dashboard/engenharia/obras/ativa/documentos',
            icon: 'paperclip',
            permission: PERMISSIONS.DOCUMENTOS_VIEW,
          },
          {
            key: 'engenharia-obras-planejamento',
            label: 'Planejamento',
            icon: 'layout-dashboard',
            children: [
              {
                key: 'engenharia-obras-ativa-planilha-contratada',
                label: 'Planilha Contratada',
                href: '/dashboard/engenharia/obras/ativa/planilha-contratada',
                icon: 'calculator',
                permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
              },
              {
                key: 'engenharia-orcamentos',
                label: 'Orçamento (referência)',
                href: '/dashboard/engenharia/orcamentos',
                icon: 'calculator',
                permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
              },
              {
                key: 'engenharia-obras-ativa-cronograma',
                label: 'Cronograma',
                href: '/dashboard/engenharia/obras/ativa/programacao-semanal',
                icon: 'calendar',
                permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
              },
              {
                key: 'engenharia-centros-custo',
                label: 'Centro de Custos',
                href: '/dashboard/engenharia/cadastros/centros-custo',
                icon: 'layers',
                permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
              },
            ],
          },
          {
            key: 'engenharia-obras-execucao',
            label: 'Execução',
            icon: 'activity',
            children: [
              {
                key: 'engenharia-obras-ativa-programacao',
                label: 'Programação Semanal',
                href: '/dashboard/engenharia/obras/ativa/programacao-semanal',
                icon: 'calendar',
                permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
              },
              {
                key: 'engenharia-obras-ativa-apropriacao',
                label: 'Apropriação',
                href: '/dashboard/engenharia/obras/ativa/apropriacao',
                icon: 'timer',
                permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
              },
              {
                key: 'engenharia-suprimentos',
                label: 'Suprimentos / Almoxarifado',
                href: '/dashboard/suprimentos/painel',
                icon: 'package',
                permission: PERMISSIONS.DASHBOARD_SUPRIMENTOS_VIEW,
              },
              {
                key: 'engenharia-equipamentos',
                label: 'Equipamentos',
                href: '/dashboard/engenharia/ativos',
                icon: 'wrench',
                permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
              },
              {
                key: 'engenharia-servicos',
                label: 'Produção / Serviços',
                href: '/dashboard/engenharia/servicos',
                icon: 'hammer',
                permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
              },
              {
                key: 'engenharia-medicoes',
                label: 'Medições (workflow)',
                href: '/dashboard/fiscalizacao/painel',
                icon: 'clipboard-check',
                permission: PERMISSIONS.DASHBOARD_FISCALIZACAO_VIEW,
              },
              {
                key: 'engenharia-produtividade',
                label: 'Produtividade',
                href: '/dashboard/rh/produtividade',
                icon: 'line-chart',
                permission: PERMISSIONS.DASHBOARD_RH_VIEW,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    key: 'licitacoes',
    label: 'Licitações',
    ordem: 4,
    items: [
      {
        key: 'licitacoes-dashboard',
        label: 'Dashboard',
        href: '/dashboard/admin/licitacoes/dashboard',
        icon: 'layout-dashboard',
        permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
        scopeTypes: ['EMPRESA'],
      },
      {
        key: 'licitacoes-gestao',
        label: 'Gestão de Licitações',
        href: '/dashboard/admin/licitacoes/gestao',
        icon: 'file-text',
        permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
        scopeTypes: ['EMPRESA'],
      },
      {
        key: 'licitacoes-kanban',
        label: 'Quadro (Kanban)',
        href: '/dashboard/admin/licitacoes/kanban',
        icon: 'columns-3',
        permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
        scopeTypes: ['EMPRESA'],
      },
      {
        key: 'licitacoes-exigencias',
        label: 'Exigências (Checklist)',
        href: '/dashboard/admin/licitacoes/exigencias',
        icon: 'list-checks',
        permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
        scopeTypes: ['EMPRESA'],
      },
      {
        key: 'licitacoes-dossie',
        label: 'Dossiê',
        href: '/dashboard/admin/licitacoes/dossie',
        icon: 'folder-open',
        permission: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
        scopeTypes: ['EMPRESA'],
      },
    ],
  },
  {
    key: 'rh',
    label: 'RH',
    ordem: 5,
    items: [
      {
        key: 'painel-rh',
        label: 'Painel RH',
        href: '/dashboard/rh/painel',
        icon: 'users',
        permission: PERMISSIONS.DASHBOARD_RH_VIEW,
        homePriority: 10,
      },
      {
        key: 'funcionarios',
        label: 'Cadastros de Pessoas',
        href: '/dashboard/rh/cadastros',
        icon: 'id-card',
        permission: PERMISSIONS.RH_FUNCIONARIOS_VIEW,
      },
      {
        key: 'presencas',
        label: 'Presenças',
        href: '/dashboard/rh/presencas',
        icon: 'clipboard-check',
        permission: PERMISSIONS.RH_PRESENCAS_VIEW,
      },
      {
        key: 'produtividade',
        label: 'Produtividade (Obra)',
        href: '/dashboard/rh/produtividade',
        icon: 'line-chart',
        permission: PERMISSIONS.DASHBOARD_RH_VIEW,
      },
    ],
  },
  {
    key: 'sst',
    label: 'SST',
    ordem: 6,
    items: [
      {
        key: 'painel-sst',
        label: 'Painel SST',
        href: '/dashboard/sst/painel',
        icon: 'shield',
        permission: PERMISSIONS.SST_PAINEL_VIEW,
        homePriority: 11,
      },
      {
        key: 'epi',
        label: 'EPI',
        href: '/dashboard/sst/epi',
        icon: 'hard-hat',
        permission: PERMISSIONS.SST_EPI_VIEW,
      },
      {
        key: 'tecnicos',
        label: 'Técnicos SST',
        href: '/dashboard/sst/tecnicos',
        icon: 'stethoscope',
        permission: PERMISSIONS.SST_TECNICOS_VIEW,
      },
      {
        key: 'checklists',
        label: 'Checklists SST',
        href: '/dashboard/sst/checklists',
        icon: 'list-checks',
        permission: PERMISSIONS.SST_CHECKLISTS_VIEW,
      },
      {
        key: 'nao-conformidades',
        label: 'Não Conformidades',
        href: '/dashboard/sst/nao-conformidades',
        icon: 'triangle-alert',
        permission: PERMISSIONS.SST_NC_VIEW,
      },
      {
        key: 'treinamentos',
        label: 'Treinamentos',
        href: '/dashboard/sst/treinamentos',
        icon: 'graduation-cap',
        permission: PERMISSIONS.SST_TREINAMENTOS_VIEW,
      },
      {
        key: 'acidentes',
        label: 'Acidentes',
        href: '/dashboard/sst/acidentes',
        icon: 'ambulance',
        permission: PERMISSIONS.SST_ACIDENTES_VIEW,
      },
    ],
  },
  {
    key: 'suprimentos',
    label: 'Suprimentos',
    ordem: 7,
    items: [
      {
        key: 'painel-suprimentos',
        label: 'Painel Suprimentos',
        href: '/dashboard/suprimentos/painel',
        icon: 'package',
        permission: PERMISSIONS.DASHBOARD_SUPRIMENTOS_VIEW,
        homePriority: 12,
      },
    ],
  },
  {
    key: 'fiscalizacao',
    label: 'Fiscalização',
    ordem: 8,
    items: [
      {
        key: 'painel-fiscalizacao',
        label: 'Painel Fiscalização',
        href: '/dashboard/fiscalizacao/painel',
        icon: 'clipboard-check',
        permission: PERMISSIONS.DASHBOARD_FISCALIZACAO_VIEW,
      },
    ],
  },
  {
    key: 'administracao',
    label: 'Administração',
    ordem: 9,
    items: [
      { key: 'organograma', label: 'Organograma', href: '/dashboard/organograma', icon: 'network', permission: PERMISSIONS.ORGANOGRAMA_VIEW },
      {
        key: 'analytics',
        label: 'Analytics / BI',
        href: '/dashboard/admin/analytics',
        icon: 'chart-column',
        permission: PERMISSIONS.ANALYTICS_VIEW,
      },
      {
        key: 'governanca-dados',
        label: 'Governança de Dados',
        href: '/dashboard/admin/governanca-dados',
        icon: 'database',
        permission: PERMISSIONS.DATA_CATALOG_VIEW,
      },
    ],
  },
  {
    key: 'relatorios',
    label: 'Relatórios',
    ordem: 10,
    items: [
      {
        key: 'relatorios-agendados',
        label: 'Relatórios Agendados',
        href: '/dashboard/relatorios/agendados',
        icon: 'calendar-clock',
        permission: PERMISSIONS.RELATORIOS_AGENDADOS_VIEW,
      },
    ],
  },
];
