import { PERMISSIONS } from '@/lib/auth/permissions';
import { REALTIME_TOPICS } from './topics';

export const REALTIME_TOPIC_PERMISSIONS: Partial<Record<string, string[]>> = {
  [REALTIME_TOPICS.MENU]: [],
  [REALTIME_TOPICS.NOTIFICATIONS]: [],
  [REALTIME_TOPICS.DASHBOARD_RH]: [PERMISSIONS.DASHBOARD_RH_VIEW],
  [REALTIME_TOPICS.DASHBOARD_SST]: [PERMISSIONS.SST_PAINEL_VIEW],
  [REALTIME_TOPICS.DASHBOARD_SUPRIMENTOS]: [PERMISSIONS.DASHBOARD_SUPRIMENTOS_VIEW],
  [REALTIME_TOPICS.DASHBOARD_ENGENHARIA]: [PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW],
  [REALTIME_TOPICS.DASHBOARD_GERENTE]: [PERMISSIONS.DASHBOARD_GERENTE_VIEW],
  [REALTIME_TOPICS.DASHBOARD_DIRETOR]: [PERMISSIONS.DASHBOARD_DIRETOR_VIEW],
  [REALTIME_TOPICS.DASHBOARD_CEO]: [PERMISSIONS.DASHBOARD_CEO_VIEW],
  [REALTIME_TOPICS.BACKUP]: [PERMISSIONS.BACKUP_VIEW],
  [REALTIME_TOPICS.RELATORIOS]: [PERMISSIONS.RELATORIOS_AGENDADOS_VIEW],
};

