CREATE TABLE automacoes_tarefas_modelos (
  id_automacao_tarefa_modelo BIGINT PRIMARY KEY AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL,
  nome_modelo VARCHAR(150) NOT NULL,
  modulo VARCHAR(30) NOT NULL,
  tipo_local VARCHAR(20) NULL,
  id_obra BIGINT NULL,
  id_unidade BIGINT NULL,
  id_setor_diretoria BIGINT NULL,
  titulo_tarefa VARCHAR(180) NOT NULL,
  descricao_tarefa TEXT NULL,
  recorrencia VARCHAR(20) NOT NULL,
  horario_execucao TIME NOT NULL,
  timezone VARCHAR(60) NOT NULL DEFAULT 'America/Sao_Paulo',
  dia_semana TINYINT NULL,
  dia_mes TINYINT NULL,
  responsavel_tipo VARCHAR(30) NOT NULL,
  id_usuario_responsavel BIGINT NULL,
  permissao_responsavel VARCHAR(120) NULL,
  gera_notificacao TINYINT(1) NOT NULL DEFAULT 1,
  gera_email TINYINT(1) NOT NULL DEFAULT 0,
  ativo TINYINT(1) NOT NULL DEFAULT 1,
  proxima_execucao_em DATETIME NULL,
  ultima_execucao_em DATETIME NULL,
  criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX ix_auto_mod_tenant (tenant_id, modulo, ativo),
  INDEX ix_auto_next (tenant_id, proxima_execucao_em, ativo)
);

CREATE TABLE automacoes_tarefas_instancias (
  id_automacao_tarefa_instancia BIGINT PRIMARY KEY AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL,
  id_automacao_tarefa_modelo BIGINT NOT NULL,
  referencia_periodo VARCHAR(30) NOT NULL,
  titulo_tarefa VARCHAR(180) NOT NULL,
  descricao_tarefa TEXT NULL,
  status_tarefa VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
  prevista_para DATETIME NOT NULL,
  id_usuario_atribuido BIGINT NULL,
  atribuido_em DATETIME NULL,
  iniciada_em DATETIME NULL,
  concluida_em DATETIME NULL,
  concluida_por_usuario BIGINT NULL,
  origem_entidade_tipo VARCHAR(60) NULL,
  origem_entidade_id BIGINT NULL,
  observacao_conclusao TEXT NULL,
  criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_tarefa_instancia_periodo (tenant_id, id_automacao_tarefa_modelo, referencia_periodo),
  INDEX ix_tarefas_usuario_status (tenant_id, id_usuario_atribuido, status_tarefa, prevista_para)
);

CREATE TABLE automacoes_sla_politicas (
  id_automacao_sla_politica BIGINT PRIMARY KEY AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL,
  nome_politica VARCHAR(150) NOT NULL,
  modulo VARCHAR(30) NOT NULL,
  chave_pendencia VARCHAR(80) NOT NULL,
  entidade_tipo VARCHAR(60) NOT NULL,
  prazo_minutos INT NOT NULL,
  alerta_antes_minutos INT NOT NULL DEFAULT 0,
  escalonar_apos_minutos INT NULL,
  max_escalacoes INT NOT NULL DEFAULT 1,
  cria_tarefa_quando_vencer TINYINT(1) NOT NULL DEFAULT 0,
  notificar_no_app TINYINT(1) NOT NULL DEFAULT 1,
  enviar_email TINYINT(1) NOT NULL DEFAULT 0,
  ativo TINYINT(1) NOT NULL DEFAULT 1,
  condicao_json JSON NULL,
  criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_sla_politica (tenant_id, modulo, chave_pendencia),
  INDEX ix_sla_tenant_mod (tenant_id, modulo, ativo)
);

CREATE TABLE automacoes_pendencias_ocorrencias (
  id_automacao_pendencia_ocorrencia BIGINT PRIMARY KEY AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL,
  id_automacao_sla_politica BIGINT NOT NULL,
  chave_deduplicacao VARCHAR(180) NOT NULL,
  modulo VARCHAR(30) NOT NULL,
  chave_pendencia VARCHAR(80) NOT NULL,
  entidade_tipo VARCHAR(60) NOT NULL,
  entidade_id BIGINT NOT NULL,
  titulo VARCHAR(180) NOT NULL,
  descricao TEXT NULL,
  status_ocorrencia VARCHAR(20) NOT NULL DEFAULT 'ABERTA',
  severidade VARCHAR(20) NOT NULL DEFAULT 'MEDIA',
  referencia_data DATETIME NULL,
  vencimento_em DATETIME NOT NULL,
  primeira_deteccao_em DATETIME NOT NULL,
  ultima_deteccao_em DATETIME NOT NULL,
  ultimo_alerta_em DATETIME NULL,
  total_alertas INT NOT NULL DEFAULT 0,
  total_escalacoes INT NOT NULL DEFAULT 0,
  id_usuario_responsavel_atual BIGINT NULL,
  rota VARCHAR(255) NULL,
  metadata_json JSON NULL,
  resolvida_em DATETIME NULL,
  criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_pendencia_dedupe (tenant_id, chave_deduplicacao),
  INDEX ix_pendencias_status (tenant_id, status_ocorrencia, severidade, vencimento_em),
  INDEX ix_pendencias_sla (tenant_id, id_automacao_sla_politica, status_ocorrencia)
);

CREATE TABLE automacoes_execucoes (
  id_automacao_execucao BIGINT PRIMARY KEY AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL,
  tipo_execucao VARCHAR(20) NOT NULL,
  status_execucao VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
  id_usuario_executor_manual BIGINT NULL,
  execucao_manual TINYINT(1) NOT NULL DEFAULT 0,
  iniciado_em DATETIME NULL,
  finalizado_em DATETIME NULL,
  total_processado INT NOT NULL DEFAULT 0,
  total_criado INT NOT NULL DEFAULT 0,
  total_notificado INT NOT NULL DEFAULT 0,
  total_escalado INT NOT NULL DEFAULT 0,
  mensagem_resultado TEXT NULL,
  criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX ix_execucoes_tenant (tenant_id, criado_em),
  INDEX ix_execucoes_status (tenant_id, status_execucao, criado_em)
);

