import { PERMISSIONS } from '@/lib/auth/permissions';
import type { PolicyAction, PolicyResource } from './types';

export const RBAC_PERMISSION_MAP: Partial<Record<PolicyResource, Partial<Record<PolicyAction, string>>>> = {
  DOCUMENTO: {
    VIEW: PERMISSIONS.DOCUMENTOS_VIEW,
    CREATE: PERMISSIONS.DOCUMENTOS_CRUD,
    UPDATE: PERMISSIONS.DOCUMENTOS_CRUD,
    DELETE: PERMISSIONS.DOCUMENTOS_CRUD,
    SIGN: PERMISSIONS.DOCUMENTOS_ASSINAR,
    EXPORT: PERMISSIONS.DOCUMENTOS_VIEW,
  },
  APROVACAO: {
    VIEW: PERMISSIONS.APROVACOES_VIEW,
    APPROVE: PERMISSIONS.APROVACOES_DECIDIR,
  },
  WORKFLOW: {
    VIEW: PERMISSIONS.WORKFLOWS_VIEW,
    EXECUTE: PERMISSIONS.WORKFLOWS_EXECUTAR,
  },
  SST_NC: {
    VIEW: PERMISSIONS.SST_NC_VIEW,
    CREATE: PERMISSIONS.SST_NC_CRUD,
    UPDATE: PERMISSIONS.SST_NC_CRUD,
    DELETE: PERMISSIONS.SST_NC_CRUD,
  },
  SST_CHECKLIST: {
    VIEW: PERMISSIONS.SST_CHECKLISTS_VIEW,
    CREATE: PERMISSIONS.SST_CHECKLISTS_CRUD,
    UPDATE: PERMISSIONS.SST_CHECKLISTS_CRUD,
    DELETE: PERMISSIONS.SST_CHECKLISTS_CRUD,
  },
  SUP_SOLICITACAO: {
    VIEW: PERMISSIONS.DASHBOARD_SUPRIMENTOS_VIEW,
  },
  ENG_MEDICAO: {
    VIEW: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
  },
  ENG_CONTRATO: {
    VIEW: PERMISSIONS.DASHBOARD_ENGENHARIA_VIEW,
  },
  ANALYTICS_DATASET: {
    VIEW: PERMISSIONS.ANALYTICS_VIEW,
    EXPORT: PERMISSIONS.ANALYTICS_EXTERNOS_VIEW,
    MANAGE: PERMISSIONS.ANALYTICS_ADMIN,
  },
  BACKUP_RESTAURACAO: {
    EXECUTE: PERMISSIONS.BACKUP_EDIT,
    VIEW: PERMISSIONS.BACKUP_VIEW,
  },
};

export function getRequiredBasePermission(resource: PolicyResource, action: PolicyAction): string | null {
  const per = RBAC_PERMISSION_MAP[resource]?.[action];
  return per ? String(per) : null;
}

